site_name: 'Tabnews Go'
site_description: 'Main documentatio for tabnew-go'
repo_url: https://github.com/kaioaresi/tabnews-go
docs_dir: docs
edit_uri: edit/main/docs


plugins:
  - techdocs-core

nav:
  - Overview:
      - Descrion of project: 'index.md'


